/******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Author: Mohamed Nasser
 *
 * Date Created: Oct 13, 2022
 *
 * Description: Source file for the ultrasonic Module driver
 *
 *******************************************************************************/

#include <util/delay.h>
#include "std_types.h"
#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"


uint8  g_counts = 0;
uint16 g_timerPeriodCounts = 0;

/*******************************************************************************
 *                     Private Functions Prototypes                            *
 *******************************************************************************/

/*
 * Description:
 * Send the Trigger pulse to the ultrasonic.
 */
static void Ultrasonic_Trigger(void);

/*
 * Description:
 * 1. This is the call back function called by the ICU driver.
 * 2. This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
static void Ultrasonic_edgeProcessing(void);

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description:
 * 1. Initialize the ICU driver as required.
 * 2. Setup the ICU call back function.
 * 3. Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	Icu_ConfigType s_congiguration = {F_CPU_8, RISING};
	Icu_init (&s_congiguration);
	Icu_setCallBack (Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection (ULTRASONIC_TRIG_PORT, ULTRASONIC_TRIG_PIN, PIN_OUTPUT);
	GPIO_writePin (ULTRASONIC_TRIG_PORT, ULTRASONIC_TRIG_PIN, LOGIC_LOW);
}

/*
 * Description:
 * Send the Trigger pulse to the ultrasonic.
 */
static void Ultrasonic_Trigger(void)
{
	GPIO_writePin (ULTRASONIC_TRIG_PORT, ULTRASONIC_TRIG_PIN, LOGIC_HIGH);
	_delay_us (11);
	GPIO_writePin (ULTRASONIC_TRIG_PORT, ULTRASONIC_TRIG_PIN, LOGIC_LOW);
}

/*
 * Description:
 * 1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2. Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance = 0;
	Ultrasonic_Trigger();
	distance = (uint16)(g_timerPeriodCounts * 0.0174);
	return distance;
}

/*
 * Description:
 * 1. This is the call back function called by the ICU driver.
 * 2. This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
static void Ultrasonic_edgeProcessing(void)
{
	g_counts++;
	switch (g_counts)
	{
	case 1:
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
		break;

	case 2:
		/* Store the Period time value + High time value */
		g_timerPeriodCounts = Icu_getInputCaptureValue();
		/* Clear the timer counter register to start measurements again */
		Icu_clearTimerValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		g_counts = 0;
	}
}
